relativeURLs = true
languageCode = "en-us"
title = "Mennecy Echange Boni"
theme = "boni-theme"
paginate = 6
image = "/Boni/small-meb.jpg"
enableInlineShortcodes = "true"

### params
[params]
  DateForm = "Mon, Jan 2, 2006"
  Description = "Mennecy (France) & Boni (Mali) : Deux Villes Solidaires"
  Presentation = "Presentation de Mennecy Echanges Boni - MEB"
  meb = "MEB - Mennecy Echanges Boni"
  email = "mennecy.echange.boni@gmail.com"
  address = "9, rue du Parc - 91540 Mennecy"
  tel= "+33678555367"
  avatarurl = "Boni/small-meb.jpg"
  presentation = "Association Essonnienne de Mennecy avec Boni au Mali"


### params social
[[params.social]]
    name = "facebook"
    icon = "fab fa-facebook"
    weight = 1
    url = "https://www.facebook.com/Mennecyechangeboni"

### taxonomie
[taxonomies]
    tag = "tags"
    category = "categories"
    mood = "moods" 
    

[markup]
    [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = "github"
      [markup.goldmark.parser.attribute]
        block = false
        title = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = false
      xhtml = false

[imaging]
# Default resample filter used for resizing. Default is Box,
# a simple and fast averaging filter appropriate for downscaling.
# See https://github.com/disintegration/imaging
resampleFilter = "box"

# Default JPEG quality setting. Default is 75.
quality = 75

# Anchor used when cropping pictures.
# Default is "smart" which does Smart Cropping, using https://github.com/muesli/smartcrop
# Smart Cropping is content aware and tries to find the best crop for each image.
# Valid values are Smart, Center, TopLeft, Top, TopRight, Left, Right, BottomLeft, Bottom, BottomRight
anchor = "smart"

# Default background color.
# Hugo will preserve transparency for target formats that supports it,
# but will fall back to this color for JPEG.
# Expects a standard HEX color string with 3 or 6 digits.
# See https://www.google.com/search?q=color+picker
bgColor = "#ffffff"

[imaging.exif]
 # Regexp matching the fields you want to Exclude from the (massive) set of Exif info
# available. As we cache this info to disk, this is for performance and
# disk space reasons more than anything.
# If you want it all, put ".*" in this config setting.
# Note that if neither this or ExcludeFields is set, Hugo will return a small
# default set.
includeFields = ""

# Regexp matching the Exif fields you want to exclude. This may be easier to use
# than IncludeFields above, depending on what you want.
excludeFields = ""

# Hugo extracts the "photo taken" date/time into .Date by default.
# Set this to true to turn it off.
disableDate = false

# Hugo extracts the "photo taken where" (GPS latitude and longitude) into
# .Long and .Lat. Set this to true to turn it off.
disableLatLong = false



  ### Analytics
  Ganalytics = ""

  # This will load all the CSS defined in the list
  # customCSS = ["<absolute path to CSS>", "/static/css/test.css", "<or just load it off the internet>"]


[menu]

  [[menu.main]]
    name = "Accueil"
    url = "/"
    weight = -200
  [[menu.main]]
    name = "Membre du bureau"
    url = "/about/"
    pre = "<i class='fa fa-chevron-right'></i>"
    weight = -180

  [[menu.main]]
    name = "Information et Adhesion"
    url = "/documents/"
    pre = "<i class='fa fa-folder'></i>"
    weight = -160


  


